### ISSUE TITLE
Card Design Implementation

### ISSUE THREAD

**Issue by VictoriaAde** [zuri-training/Proj-CC_gen-Team-124#20]
### Task Description

These are the [cards](https://www.figma.com/file/yD5F6g67uY8Gj6GytXXj9S/Team-124-cc_gen-Wireframes?node-id=4%3A98) you are implementing, you are to use the BEM naming convention in naming your classes.
I have added a base.css file, read the comments in the file.
Create a branch called **card-design**
Make sure your commit message is clear and descriptive.

**NB: Your pull request would be merged only if you do the above.**

Good luck 👍 

![Image](https://user-images.githubusercontent.com/60205816/182357477-faee536e-86e4-435b-8e25-cae94d4bffc6.png)

**Comment by muakone** [comment]
noted
