### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by VictoriaAde** [zuri-training/Proj-CC_gen-Team-124#3]
### Design company Logo.
The following are the suggested names for our product
* CCVilla 
* Credina
* Credard

### Your task is to create a logo based on these names, so we can choose the logo that works

**Comment by Jehohshua** [comment]
I created a _Logo_ and _color_ palette for the name **Credard**
[Check it out here](https://www.figma.com/file/yD5F6g67uY8Gj6GytXXj9S/Team-124-cc_gen-Wireframes?node-id=338%3A585)
