### ISSUE TITLE
Documentation for Project Presentation

### ISSUE THREAD

**Issue by VictoriaAde** [zuri-training/Proj-CC_gen-Team-124#4]
## Task:

You will work on an extended version of this [`Document`](https://docs.google.com/document/d/1tKblptqX08gQyZSJ0Czna7JrrUVoNyeVGIdM_KYBVyE/edit)

**NB:** Any document you create should be inside this [Drive Folder](https://drive.google.com/drive/folders/1RQHJ0DsLYq2ftd-4rEm5lqPWG3zMfsv5)

**Comment by whitesoftx** [comment]
I've started something, let's collaborate to work on the file. Here is the file [Documentation for Project Presentation](https://docs.google.com/document/d/1DWA4ZwdISgN0JvuIN36B516YIxWYqzoncjOXI4zbpQM/edit?usp=sharing)

**Comment by Odili1** [comment]
@whitesoftx I have gone through the Document. Nice start.
