### ISSUE TITLE
Wire Frame

### ISSUE THREAD

**Issue by VictoriaAde** [zuri-training/Proj-CC_gen-Team-124#6]
This is needed for the presentation due on friday

**Comment by Dezignss** [comment]
Completed

**Comment by Jehohshua** [comment]
I have worked on the pages assigned to me
[You'll find them here](https://www.figma.com/file/yD5F6g67uY8Gj6GytXXj9S/Team-124-cc_gen-Wireframes?node-id=0%3A1)
