### ISSUE TITLE
HF - Forgot password page

### ISSUE THREAD

**Issue by Jehohshua** [zuri-training/Proj-CC_gen-Team-124#64]

**Comment by Reucy** [comment]
I worked on the Low fidelity wireframe of my team. here are the links:

https://www.figma.com/file/yD5F6g67uY8Gj6GytXXj9S/Team-124-cc_gen-Wireframes?node-id=1241%3A61947
https://www.figma.com/file/yD5F6g67uY8Gj6GytXXj9S/Team-124-cc_gen-Wireframes?node-id=1172%3A54138
https://www.figma.com/file/yD5F6g67uY8Gj6GytXXj9S/Team-124-cc_gen-Wireframes?node-id=1172%3A54436
https://www.figma.com/file/yD5F6g67uY8Gj6GytXXj9S/Team-124-cc_gen-Wireframes?node-id=1172%3A53839
