### ISSUE TITLE
reseet password page wireframe

### ISSUE THREAD

**Issue by Jehohshua** [zuri-training/Proj-CC_gen-Team-124#73]

**Comment by Reucy** [comment]
I worked on the Low fi  of Reset password page. Here are links.


https://www.figma.com/file/yD5F6g67uY8Gj6GytXXj9S/Team-124-cc_gen-Wireframes?node-id=492%3A324
https://www.figma.com/file/yD5F6g67uY8Gj6GytXXj9S/Team-124-cc_gen-Wireframes?node-id=493%3A349
https://www.figma.com/file/yD5F6g67uY8Gj6GytXXj9S/Team-124-cc_gen-Wireframes?node-id=496%3A381
https://www.figma.com/file/yD5F6g67uY8Gj6GytXXj9S/Team-124-cc_gen-Wireframes?node-id=502%3A588
